### ISSUE TITLE
About App Academy Open

### ISSUE THREAD

**Issue by garymdurante** [fiosman/App-Academy#3]
First and foremost, congratulations for completing App Academy Online Curriculum.
I'm in awe really that you made it through.

By the way, just like to ask a question.  Do you already have a programming background? years or months of experience before tackling App Academy?

I'd completed the Intro to Programming, and now I'm on the last section of Software Engineering Foundations i.e. Additional Projects... I'm also self-taught, I went through each exercises using my own solution, it's pretty challenging and time consuming, I've learned a lot though. 

I also have a day job, seems it will take me approx 2 years to complete App Academy Open, I'm doing it a couple of hours in the evening & also couple of hours very early in the morning.

I already like Ruby, readability and chaining especially. However once in a while it bugs me whether to continue learning Ruby Stack or just head straight to JavaScript Stack, a piece of advice would help.

Congrats again.

**Comment by fiosman** [comment]
Hi there! 

Thanks for your message. See below my responses

1. No programming background prior to App Academy. 
2. You will get the most out of the program by doing each challenge on your own. Even if you get stuck, keep at it. Don't look at the solution as tempting as that may be! By utilizing this approach your understanding of the material will be even deeper than those doing the in-person, because they do not have the time to complete each project. 
3. It took me 1 year and 7 months. I studied every day for about 3 hours, except Saturdays and Sundays when I'd spend about 8 hours each. I know it's tough, but in my honest opinion you should not quit your job to do this full time. Just go slow and easy. Learn at your own pace. 
4. I HIGHLY advise you not to jump into the JS section without completing Ruby. You will torture yourself. A lot of the later on projects in the JS section requires you to have an understanding of CS fundamentals, specifically OOP and you learn that in Ruby.  Plus React/Rails/SQL sections require you to know Ruby. You won't be able to do the projects without knowledge of Ruby. I think it took me a good 5-6 months to do the Ruby curriculum on its own. It was a pain, by far the hardest section. Take it from me, if you use the same learning method you are doing in the Alpha course, you WILL be able to finish the Ruby curriculum. 

I hope my responses help. Let me know if you have any further questions and thanks again!

**Comment by garymdurante** [comment]
Thanks for the input especially for someone who went through great lengths to complete App Academy.
Its not that easy to just take an advice right away from someone who hasn't completed aA, well that is until today.

Now I know my workaround.
Thank you very much.
